version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: fct_visitation_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Home321Home@
      MYSQL_ROOT_PASSWORD: Home321Home@
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/db:/docker-entrypoint-initdb.d

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fct_visitation_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Home321Home@
    depends_on:
      - mysql

volumes:
  mysql_data: